import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/components/header";
import { ClientThemeWrapper, ThemeProvider } from "@/components/themeController";
import Footer from "@/components/footer";
import { StoreProvider } from "@/components/providers";
import { ToastContainer } from 'react-toastify';
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        suppressHydrationWarning
      >

        <ThemeProvider>
          <ClientThemeWrapper>
            <StoreProvider>
              <div className="lg:mx-24 text-2xl h-full">
                <Header></Header>
                {children}
                <Footer></Footer>
                <ToastContainer></ToastContainer>
              </div>
            </StoreProvider>
          </ClientThemeWrapper>
        </ThemeProvider>

      </body>
    </html>
  );
}
